### ISSUE TITLE
Not sending anything to the server. 

### ISSUE THREAD

**Issue by JohnnyBravo-99** [DJWoodZ/FS22-Discord-Bot#11]
Not sure what is going on here but i feel like I am missing something.

TypeError: fetch failed
    at node:internal/deps/undici/undici:12618:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: AggregateError [ECONNREFUSED]:
      at internalConnectMultiple (node:net:1116:18)
      at afterConnectMultiple (node:net:1683:7) {
    code: 'ECONNREFUSED',
    [errors]: [ [Error], [Error] ]
  }
}

**Comment by DJWoodZ** [comment]
Hi,

That error suggest that the `FS22_BOT_URL_CAREER_SAVEGAME` or `FS22_BOT_URL_SERVER_STATS` values have either not been specified correctly or are unreachable. Verify that you can reach the URLs from the host/container you using to run the bot.

**Comment by JohnnyBravo-99** [comment]
Alright well now that has stopped and it just keeps saying updating in the GIT console. Will it send a message to the console once it has successfully sent something to the server or is Updating the only console feedback? My discord server/channel isn't receiving anything from the bot.

**Comment by DJWoodZ** [comment]
Yes, the bot will regularly poll the server according to the `FS22_BOT_POLL_INTERVAL_MINUTES` setting which, by default, is set to 1 minute. When it does that, you will see 'Updating...' in the console. If the bot detects a change (such as a new player having joined the server), it will say 'Sending message to: ...' in the console. A message should then appear in Discord and, if relevant, the bot's status will also be updated to reflect the new player count, e.g. 'Playing online: 1/4'.

If no messages are appearing when a player joins/leaves the server and you have specified `FS22_BOT_DISCORD_SERVER_NAME` and/or `FS22_BOT_DISCORD_CHANNEL_NAME` values, ensure they are spelled correctly, especially if they contain special characters, as the bot will only send messages if it is connected to a server with that name and/or channel name.

By default, the bot will post to all channels it can access. So, an alternative approach to manage the channels it posts to, would be to leave `FS22_BOT_DISCORD_SERVER_NAME` and `FS22_BOT_DISCORD_CHANNEL_NAME` blank and use roles/permissions in your Discord server to control the channels the bot appears in/posts to.
