### ISSUE TITLE
my bot not working any help ?

### ISSUE THREAD

**Issue by gabryah69** [DJWoodZ/FS22-Discord-Bot#13]
hello :D i try to install my discord bot but i have the same error token invalid i don't know why becose i put my discord token correct and y make 3 new discord token and new bot on devolopers site but say the same error any help ? 
![error](https://github.com/DJWoodZ/FS22-Discord-Bot/assets/65086005/fcbd5594-fe47-4a39-a78e-798e8646193f)
thanks for your bot ! :D

**Comment by DJWoodZ** [comment]
Hi @gabryah69,

It looks like you were trying to run the bot from this working directory:

`C:\Users\gabri\Desktop\FS22-Discord-Bot-main\FS22-Discord-Bot\`

But it looks like you were editing the `.env.local` in the directory above:

`C:\Users\gabri\Desktop\FS22-Discord-Bot-main\.env.local`

If you run the bot from `C:\Users\gabri\Desktop\FS22-Discord-Bot-main\FS22-Discord-Bot\`, you must edit `C:\Users\gabri\Desktop\FS22-Discord-Bot-main\FS22-Discord-Bot\.env.local`.

Similarly, if you run the bot from `C:\Users\gabri\Desktop\FS22-Discord-Bot-main\`, you must edit `C:\Users\gabri\Desktop\FS22-Discord-Bot-main\.env.local`.
